project_id = "vmsdalzjlkuilzcetztv"

[functions.send-daily-etymology]
verify_jwt = false

[functions.record-etymology-feedback]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.confirm-subscription]
verify_jwt = false